language: node_js
node_js:
  - 12.9.1
cache:
  directories:
    - node_modules
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - yarn
script:
  - npm run build
deploy:
  provider: script
  script: aws s3 sync --cache-control max-age=259200 --region ap-northeast-1 --delete build s3://sjmyuan-ganggang-editor
  skip_cleanup: true
env:
  global:
    - secure: fJ29w7tsygeudS3F6q8OLQDIbfVbWhD3Y4RaaK/7xGR3rojeXo5TScgQg6AN/vZ8jdAOOoT2CVcnsSx9cq1AC1l9alt4v1lq8SInAdiqNoswt2vyYmlT8LjHOA4jX0OdpMNxpu2pqnoqnv1OARpeoNu3FyzHhkDhWcc8udsLAyI58P0TcShqUqooVhA8/XXn0jeG6vtIp7+DXXowavEj3ciaZNp6gVH5ERgHxD0rhK2ueKQzFilCqfj4a4QXIwXj+JN3AKBzUfqGGxMBUG9A3/mzj419q5ZDQEA5YI3Yqsr4GRAwMSkXgn7b69yqszXgMfMHPZr+6jAVDZ3GOhXFosFS2JYylgMw9EoNw6PJ/xjqCO7arT7SsrcWz6ML0uX+4JR/At4+x8FnSJzDIYiZdwQGf5iJUSrVM1YEyAtnkQq8BMCoiqVHPCts/iVhoSXIJsF4CVSXYc+Wev7t2mye7/fmAfmZk/9xfzf/YBXQysQ9ynap7GSAuH8NNtcuhXPCiyzC4TMhnr9RP2MVcAc9rRH9BnePvlmt0GGsshu9N6WYmTsCBCbM1MpAYuadFgLRTfbmoW+iveav8TQvlhHMX9Q/GGLz7t3zqFM6hiNoyEjwpTMWVIQIrSUStFUDCNAIHfN1LJEPDfb+8/LALo7OOGAIAmNgAglyElkoXTkvSy0=
    - secure: haSm8nRx0Zkb+6d/Uxb+mqkaxA+ByU165p8Rr2JXf+Zb3iOjFSf6DwD+DxXARt/2hrxHnMw1bIgIMcrOH6lPGsTvapFLSdpZWvMgysaCyPLyqQ4Uj94DYnIuEAse8o1gZb0GHkGtwLNBKsM+FMCW/Zuxw5epuhRfouJxTkWPnZsNDLlN++6/uahQDYGffnsZenpHQmHvAAZeW5RMe16ko7R4FbgsBp6/3X+Hs3XniRjccSF3zsCXoa91aBz/1Z5/7HCehBlAVy7i56dE6xFwHg/iHqpzN5y7lQrL3NTBXzr4//Fpf1YwIMQLUSjvSNOY9Sc9k/GcFxDRs8mmvDA6Q4Fv51mdMfHeJmluASxwWJ+KGJaDMjPafqVToTRrxrX2pJc+ApRjXqyLLPV2Bj0VtKXvnaGiVWGUN+4UgZYRa5FUbzKn60WLMhuBwV0BaCG4zFbXZjEyLzc5s/Xf44HCX1/l0FFQIqU9Trj7Iw6ElRXl2dKF3u9UMoI1Cx1VIsAISfWpgkOAYAA1MaRmSp2qbT2K+xLoDjAHmyeHcTUD+Jjs8Zr4GWcdrsq9htnaDuu/nBHzrJMp4ggtCBeF6HkwD2IiL2fMjw7J+RS8BhpSa9CK21XbRTeuJZnjtvk9Iu4/S8+T9qDPtA3mtqDxMuP98HcQUK8kXpxvCZLkIqnMA6Y=
